server {
    listen 8083;

    location /FR {
        proxy_pass https://194.33.34.66:443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    location /GB {
        proxy_pass https://89.169.53.227:443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    
    # Optional: Add a default location for other paths, or NGINX will return 404
    location / {
        return 404; # Or serve a default page, or redirect
    }
}
