server {
    # gRPC HTTP/2 gerektirir. http2 parametresi eklenmeli.
    listen 8080 http2;

    # gRPC istekleri genelde application/grpc content-type ile gelir
    location /DE {
        grpc_pass grpc://138.124.118.130:80;
        # Metadata aktarımı (gRPC'te header'lar metadata olarak geçer)
        grpc_set_header Host $host;
    }

    location /FR {
        grpc_pass grpc://194.33.34.66:80;
        grpc_set_header Host $host;
    }

    location /US {
        grpc_pass grpc://77.73.238.101:80;
        grpc_set_header Host $host;
    }

    location / {
        return 404;
    }
}
