server {
    listen 8080;

    location /DE {
        proxy_pass http://89.169.53.227:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    location /FR {
        proxy_pass http://194.33.34.66:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    location /US {
        proxy_pass http://45.61.163.95:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    
    # Optional: Add a default location for other paths, or NGINX will return 404
    location / {
        return 404; # Or serve a default page, or redirect
    }
}
